### ISSUE TITLE
[LibraryLoader] Breaking change in v3.0.2 release

### ISSUE THREAD

**Issue by vlohachov** [cricut/FishyJoes#104]
Right now android Foundation app build fails due to this change:

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/115993681/230566749-a2226266-c9f0-4273-9ce8-20297abacadd.png">

<img width="499" alt="image" src="https://user-images.githubusercontent.com/115993681/230566894-34675bcc-54ff-4fb1-b8f3-a354241aec00.png">

Can somebody help with migration steps?

**Comment by vlohachov** [comment]
Did I get it right that we need to create following object inside Foundation project:

```kotlin
object FoundationLibraryRepresentative : LibraryLoader.LibraryRepresentative {
    override fun ensureLoaded() { }
    override val dependencies: List<LibraryLoader.LibraryRepresentative>
        get() = listOf(CriGeoLoaderRepresentative)
    override val nativeLibs: List<String>
        get() = emptyList()

    init {
        LibraryLoader.loadRepresentative(this)
    }
}
```

And completely remove this `loadCrigeoNativeLibraries()` function after?

**Comment by cobbal** [comment]
Calling "ensureLoaded" manually was a temporary workaround. 3.0 has proper non-deadlocking loading, and the workaround can be entirely deleted.
