### ISSUE TITLE
Desktop app exception: "TODO: implement Swift.Set.static func fromNode(_:env:)"

### ISSUE THREAD

**Issue by iiaremenko** [cricut/FishyJoes#175]
Hello,

our Desktop client of CriCanvas receiving following exception:`TODO: implement Swift.Set.static func fromNode(_:env:)`. 

Exception thrown here:
https://github.com/cricut/FishyJoes/blob/6cca54724618940755bea56febb987fc3c9f7514/Sources/FishyJoesNodeRuntime/NodeConverter.swift#L324

Could you please advise how we can avoid this exception in CriCanvas? Or maybe there is a plan to implement this function? or maybe we can just avoid using some function that is currently not supported by the FishyJoes?

Desktop exception:
<img width="827" alt="image (1)" src="https://github.com/cricut/FishyJoes/assets/84372502/8c47900c-4bc6-4025-a97c-389303f989a5">

<img width="898" alt="image" src="https://github.com/cricut/FishyJoes/assets/84372502/9db06707-559b-4643-9daa-98efcfc35a64">

**Comment by cobbal** [comment]
Looks like passing sets (and dictionaries maybe?) from node -> swift is something that fell through the cracks. We should get that working.
